# Generated by Django 5.2.7 on 2025-10-31 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Docente', '0003_alter_curso_curso_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Cuestionario')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(max_length=200, verbose_name='Enunciado Pregunta')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.cuestionario')),
            ],
        ),
    ]
