# Generated by Django 5.2.7 on 2025-11-22 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Cuestionario')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.curso')),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado Pregunta')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.cuestionario')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['id', 'enunciado'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('retro', models.TextField(verbose_name='Retroalimentación')),
                ('ID_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.preguntas')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['id'],
            },
        ),
    ]
