# Generated by Django 5.2.7 on 2025-11-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='nombre',
            field=models.CharField(choices=[('Inicial', 'Cuestionario inicial'), ('Final', 'Cuestionario final')], default='Cuestionario inicial', max_length=100, verbose_name='Nombre Cuestionario'),
        ),
    ]
