# Generated by Django 5.2.7 on 2025-10-31 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='enunciado',
            field=models.TextField(verbose_name='Enunciado Pregunta'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('retro', models.TextField(verbose_name='Retroalimentación')),
                ('ID_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.preguntas')),
            ],
        ),
        migrations.AddField(
            model_name='preguntas',
            name='tipo_respuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.tipo_respuesta'),
            preserve_default=False,
        ),
    ]
