# Generated by Django 5.2.7 on 2025-12-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionario', '0002_alter_cuestionario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='retro',
            field=models.TextField(verbose_name='Alternativa'),
        ),
    ]
