# Generated by Django 5.2.7 on 2025-11-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionario', '0002_tipo_respuesta_alter_preguntas_enunciado_respuesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntas',
            name='tipo_respuesta',
        ),
        migrations.AlterModelOptions(
            name='cuestionario',
            options={'verbose_name': 'Cuestionario', 'verbose_name_plural': 'Cuestionarios'},
        ),
        migrations.AlterModelOptions(
            name='preguntas',
            options={'ordering': ['enunciado'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.DeleteModel(
            name='Tipo_Respuesta',
        ),
    ]
