# Generated by Django 5.2.7 on 2025-11-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionario', '0003_remove_preguntas_tipo_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuestionario',
            options={'ordering': ['id'], 'verbose_name': 'Cuestionario', 'verbose_name_plural': 'Cuestionarios'},
        ),
        migrations.AlterModelOptions(
            name='preguntas',
            options={'ordering': ['id', 'enunciado'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['id'], 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
    ]
