# Generated by Django 5.2.7 on 2025-11-24 14:18

import Applications.Docente.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_docente', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-\\.]*$', 'Este campo solo puede contener letras y espacios.')], verbose_name='Nombre Docente')),
                ('apellido_docente', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-\\.]*$', 'Este campo solo puede contener letras y espacios.')], verbose_name='Apellido Docente')),
                ('asignatura_docente', models.CharField(max_length=150, verbose_name='Asignatura')),
                ('pais_docente', models.CharField(choices=[('CL', 'Chile'), ('AR', 'Argentina'), ('BR', 'Brasil'), ('PE', 'Peru'), ('OTRO', 'Otro')], default='Chile', max_length=150, verbose_name='País Docente')),
                ('foto_perfil_docente', models.ImageField(blank=True, null=True, upload_to='perfiles/docentes/', validators=[Applications.Docente.models.validacion_imagen], verbose_name='Foto perfil docente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['apellido_docente', 'nombre_docente'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_Curso', models.CharField(max_length=150, verbose_name='Nombre del Curso')),
                ('Descripcion_del_curso', models.TextField(max_length=1000, verbose_name='Descripción del Curso')),
                ('Descripcion_breve_del_curso', models.TextField(max_length=150, verbose_name='Breve Descripción')),
                ('fecha_realización_curso', models.DateField(verbose_name='Fecha Realización Curso')),
                ('paralelo_curso', models.IntegerField(verbose_name='Paralelo Curso')),
                ('curso_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.docente')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['fecha_realización_curso', 'nombre_del_Curso'],
            },
        ),
    ]
