# Generated by Django 5.2.7 on 2025-10-30 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_docente', models.CharField(max_length=150, verbose_name='Nombre Docente')),
                ('apellido_docente', models.CharField(max_length=150, verbose_name='Apellido Docente')),
                ('asignatura_docente', models.CharField(max_length=150, verbose_name='Asignatura')),
                ('pais_docente', models.CharField(max_length=150, verbose_name='País Docente')),
                ('foto_perfil_docente', models.Field()),
                ('correo_docente', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('contrasena_docente', models.CharField(max_length=150, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_Curso', models.CharField(max_length=150, verbose_name='Nombre del Curso')),
                ('Descripcion_del_curso', models.TextField(max_length=150, verbose_name='Descripción del Curso')),
                ('fecha_realización_curso', models.DateField(verbose_name='Fecha Realización Curso')),
                ('paralelo_curso', models.CharField(verbose_name='Paralelo Curso')),
                ('curso_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.docente')),
            ],
        ),
    ]
