# Generated by Django 5.2.7 on 2025-12-12 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Docente.docente'),
        ),
    ]
