# Generated by Django 5.2.7 on 2025-10-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='contrasena_docente',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='foto_perfil_docente',
        ),
        migrations.AlterField(
            model_name='curso',
            name='paralelo_curso',
            field=models.CharField(max_length=10, verbose_name='Paralelo Curso'),
        ),
    ]
