# Generated by Django 5.2.7 on 2025-11-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='Descripcion_breve_del_curso',
            field=models.TextField(default=0.0005, max_length=150, verbose_name='Breve Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='Descripcion_del_curso',
            field=models.TextField(max_length=1000, verbose_name='Descripción del Curso'),
        ),
    ]
