# Generated by Django 5.2.7 on 2025-11-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0002_curso_descripcion_breve_del_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='correo_docente',
            field=models.EmailField(default=0.0005, max_length=254, unique=True, verbose_name='Correo Electronico'),
            preserve_default=False,
        ),
    ]
