# Generated by Django 5.2.7 on 2025-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0002_remove_docente_contrasena_docente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='contrasena_docente',
            field=models.CharField(default=1, max_length=150, verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='foto_perfil_docente',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/docentes/', verbose_name='Foto perfil docente'),
        ),
    ]
