# Generated by Django 5.2.7 on 2025-12-12 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0002_alter_curso_curso_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='curso_docente',
        ),
        migrations.AddField(
            model_name='docente',
            name='curso_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='Docente.curso'),
        ),
    ]
