# Generated by Django 5.2.7 on 2025-12-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0003_remove_curso_curso_docente_docente_curso_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='curso_principal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='Docente.curso'),
        ),
    ]
