# Generated by Django 5.2.7 on 2025-11-13 00:34

import Applications.Docente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0003_docente_contrasena_docente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='foto_perfil_docente',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/docentes/', validators=[Applications.Docente.models.validacion_imagen], verbose_name='Foto perfil docente'),
        ),
    ]
