# Generated by Django 5.2.7 on 2025-11-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0004_alter_docente_foto_perfil_docente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['fecha_realización_curso', 'nombre_del_Curso'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['apellido_docente', 'nombre_docente'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
    ]
