# Generated by Django 5.2.7 on 2025-11-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0005_alter_curso_options_alter_docente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='paralelo_curso',
            field=models.IntegerField(max_length=10, verbose_name='Paralelo Curso'),
        ),
    ]
