# Generated by Django 5.2.7 on 2025-11-20 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0006_alter_curso_paralelo_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='paralelo_curso',
            field=models.IntegerField(verbose_name='Paralelo Curso'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='apellido_docente',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-\\.]*$', 'Este campo solo puede contener letras y espacios.')], verbose_name='Apellido Docente'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre_docente',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-\\.]*$', 'Este campo solo puede contener letras y espacios.')], verbose_name='Nombre Docente'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='pais_docente',
            field=models.CharField(choices=[('Chile', 'Chile'), ('Argentina', 'Argentina'), ('Brasil', 'Brasil'), ('Peru', 'Peru'), ('Otro', 'Otro')], default='Chile', max_length=150, verbose_name='País Docente'),
        ),
    ]
