# Generated by Django 5.2.7 on 2025-11-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0007_alter_curso_paralelo_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='pais_docente',
            field=models.CharField(choices=[('CL', 'Chile'), ('AR', 'Argentina'), ('BR', 'Brasil'), ('PE', 'Peru'), ('OTRO', 'Otro')], default='Chile', max_length=150, verbose_name='País Docente'),
        ),
    ]
