# Generated by Django 5.2.7 on 2025-11-22 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0008_alter_docente_pais_docente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='contrasena_docente',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='correo_docente',
        ),
        migrations.AddField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
