# Generated by Django 5.2.7 on 2025-10-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=150, verbose_name='Nombre Estudiante')),
                ('apellido_estudiante', models.CharField(max_length=150, verbose_name='Apellido_Estudiante')),
                ('correo_estudiante', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('pais_estudiante', models.CharField(max_length=150, verbose_name='País Docente')),
                ('foto_perfil_estudiante', models.Field()),
                ('contrasena_estudiante', models.CharField(max_length=150, verbose_name='Contraseña Estudiante')),
            ],
        ),
    ]
