# Generated by Django 5.2.7 on 2025-11-24 14:18

import Applications.Estudiante.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Caso_Clinico', '0001_initial'),
        ('Docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-\\.]*$', 'Este campo solo puede contener letras y espacios.')], verbose_name='Nombre Estudiante')),
                ('apellido_estudiante', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-\\.]*$', 'Este campo solo puede contener letras y espacios.')], verbose_name='Apellido Estudiante')),
                ('correo_estudiante', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('pais_estudiante', models.CharField(choices=[('Chile', 'Chile'), ('Argentina', 'Argentina'), ('Brasil', 'Brasil'), ('Peru', 'Peru'), ('Otro', 'Otro')], default='Chile', max_length=150, verbose_name='País Estudiante')),
                ('foto_perfil_estudiante', models.ImageField(blank=True, null=True, upload_to='perfiles/estudiantes/', validators=[Applications.Estudiante.models.validacion_imagen], verbose_name='Foto perfil estudiante')),
                ('contrasena_estudiante', models.CharField(max_length=150, verbose_name='Contraseña Estudiante')),
                ('cursos', models.ManyToManyField(blank=True, related_name='cursos_estudiantes', to='Docente.curso')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellido_estudiante', 'nombre_estudiante'],
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_progreso_inicial', models.DateField(verbose_name='Fecha de Progreso de Inicio')),
                ('fecha_progreso_termino', models.DateField(verbose_name='Fecha de Progreso de Termino')),
                ('puntaje_obtenido_inicial', models.FloatField()),
                ('puntaje_obtenido_final', models.FloatField()),
                ('porcentaje_progreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video_visto', models.BooleanField(default=False)),
                ('docente_Correspondiente_progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.docente')),
                ('etapa_completada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.etapa')),
                ('parte_cuerpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.partes_cuerpo')),
                ('progreso_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.curso')),
                ('progreso_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante')),
            ],
            options={
                'verbose_name': 'Progreso',
                'verbose_name_plural': 'Progresos',
            },
        ),
    ]
