# Generated by Django 5.2.7 on 2025-11-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0002_curso_descripcion_breve_del_curso_and_more'),
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='curso_estudiante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='cursos_estudiantes', to='Docente.curso'),
        ),
    ]
