# Generated by Django 5.2.7 on 2025-11-29 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionario', '0001_initial'),
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.cuestionario')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.preguntas')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta Estudiante',
                'verbose_name_plural': 'Respuestas Estudiantes',
                'unique_together': {('estudiante', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField()),
                ('porcentaje', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionario.cuestionario')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante')),
            ],
            options={
                'verbose_name': 'Resultado Cuestionario',
                'verbose_name_plural': 'Resultados Cuestionarios',
                'unique_together': {('estudiante', 'cuestionario')},
            },
        ),
    ]
