# Generated by Django 5.2.7 on 2025-10-31 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0002_remove_docente_contrasena_docente_and_more'),
        ('Estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='curso_estudiante',
            field=models.ForeignKey(default=0.0004938271604938272, on_delete=django.db.models.deletion.CASCADE, to='Docente.curso'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_progreso_inicial', models.DateField(verbose_name='Fecha de Progreso de Inicio')),
                ('fecha_progreso_termino', models.DateField(verbose_name='Fecha de Progreso de Termino')),
                ('puntaje_obtenido_inicial', models.FloatField()),
                ('puntaje_obtenido_final', models.FloatField()),
                ('porcentaje_progreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('docente_Correspondiente_progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.docente')),
                ('progreso_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.curso')),
                ('progreso_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante')),
            ],
        ),
    ]
