# Generated by Django 5.2.7 on 2025-10-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0002_estudiante_curso_estudiante_progreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='foto_perfil_estudiante',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
