# Generated by Django 5.2.7 on 2025-10-31 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0004_alter_estudiante_foto_perfil_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='foto_perfil_estudiante',
        ),
    ]
