# Generated by Django 5.2.7 on 2025-10-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0005_remove_estudiante_foto_perfil_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto_perfil_estudiante',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/estudiantes/', verbose_name='Foto perfil estudiante'),
        ),
    ]
