# Generated by Django 5.2.7 on 2025-10-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0006_estudiante_foto_perfil_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apellido_estudiante',
            field=models.CharField(max_length=150, verbose_name='Apellido Estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='pais_estudiante',
            field=models.CharField(max_length=150, verbose_name='País Estudiante'),
        ),
    ]
