# Generated by Django 5.2.7 on 2025-11-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0007_alter_estudiante_apellido_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['apellido_estudiante', 'nombre_estudiante'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
    ]
