# Generated by Django 5.2.7 on 2025-11-13 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0005_alter_curso_options_alter_docente_options'),
        ('Estudiante', '0008_alter_estudiante_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='curso_estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Docente.curso'),
        ),
    ]
