# Generated by Django 5.2.7 on 2025-11-20 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiante', '0009_alter_estudiante_curso_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apellido_estudiante',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-\\.]*$', 'Este campo solo puede contener letras y espacios.')], verbose_name='Apellido Estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre_estudiante',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-\\.]*$', 'Este campo solo puede contener letras y espacios.')], verbose_name='Nombre Estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='pais_estudiante',
            field=models.CharField(choices=[('Chile', 'Chile'), ('Argentina', 'Argentina'), ('Brasil', 'Brasil'), ('Peru', 'Peru'), ('Otro', 'Otro')], default='Chile', max_length=150, verbose_name='País Estudiante'),
        ),
    ]
