# Generated by Django 5.2.7 on 2025-11-20 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0014_alter_partes_cuerpo_partecuerpo'),
        ('Estudiante', '0010_alter_estudiante_apellido_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progreso',
            options={'verbose_name': 'Progreso', 'verbose_name_plural': 'Progresos'},
        ),
        migrations.AddField(
            model_name='progreso',
            name='etapa_completada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.etapa'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='parte_cuerpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.partes_cuerpo'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='video_visto',
            field=models.BooleanField(default=False),
        ),
    ]
