# Generated by Django 5.2.7 on 2025-11-21 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0008_alter_docente_pais_docente'),
        ('Estudiante', '0011_alter_progreso_options_progreso_etapa_completada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='curso_estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Docente.curso'),
        ),
    ]
