# Generated by Django 5.2.7 on 2025-10-31 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Docente', '0002_remove_docente_contrasena_docente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Caso_clinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.CharField(max_length=100, verbose_name='Nombre Caso')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Etapa')),
                ('video', models.URLField()),
                ('pregunta', models.CharField(max_length=150, verbose_name='Pregunta Etapa')),
                ('Caso_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.caso_clinico')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Partes_cuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParteCuerpo', models.CharField(max_length=100, verbose_name='Parte del cuerpo')),
                ('Etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.etapa')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retroalimentacion', models.CharField(max_length=200, verbose_name='Retroalimentación')),
                ('correcta', models.BooleanField(verbose_name='Correcta')),
                ('Etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.etapa')),
            ],
        ),
    ]
