# Generated by Django 5.2.7 on 2025-11-24 14:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Paciente')),
                ('edad', models.IntegerField(verbose_name='Edad Paciente')),
                ('ocupacion', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-\\.]*$', 'Este campo solo puede contener letras y espacios.')], verbose_name='Ocupación')),
                ('prevision', models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Particular', 'Particular/Privado'), ('Otro', 'Otro'), ('No aplica', 'No aplica')], default='FONASA', max_length=50, verbose_name='Previsión')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['fecha_nacimiento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Caso_clinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso', models.CharField(max_length=100, verbose_name='Nombre Caso')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docente.curso')),
            ],
            options={
                'verbose_name': 'Caso clínico',
                'verbose_name_plural': 'Casos clínicos',
            },
        ),
        migrations.CreateModel(
            name='Partes_cuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParteCuerpo', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-\\.]*$', 'Este campo solo puede contener letras y espacios.')], verbose_name='Parte del cuerpo')),
                ('CasoClinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.caso_clinico')),
            ],
            options={
                'verbose_name': 'Parte del cuerpo',
                'verbose_name_plural': 'Partes del cuerpo',
                'unique_together': {('ParteCuerpo', 'CasoClinico')},
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Etapa')),
                ('video', models.URLField(blank=True, null=True)),
                ('ParteCuerpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.partes_cuerpo')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['nombre', 'ParteCuerpo'],
            },
        ),
        migrations.CreateModel(
            name='Partes_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.pacientes')),
                ('ParteCuerpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.partes_cuerpo')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pregunta Etapa')),
                ('Etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.etapa')),
            ],
            options={
                'verbose_name': 'Pregunta etapa',
                'verbose_name_plural': 'Preguntas etapa',
                'ordering': ['id', 'Etapa'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retroalimentacion', models.CharField(max_length=200, verbose_name='Retroalimentación')),
                ('correcta', models.BooleanField(verbose_name='Correcta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.preguntaetapa')),
            ],
            options={
                'verbose_name': 'Respuesta etapa',
                'verbose_name_plural': 'Respuestas etapa',
                'ordering': ['id', 'pregunta'],
            },
        ),
    ]
