# Generated by Django 5.2.7 on 2025-12-06 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Etapa', 'verbose_name_plural': 'Etapas'},
        ),
        migrations.AddField(
            model_name='etapa',
            name='orden',
            field=models.IntegerField(default=0, null=True, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='tema',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tema específico'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='tipo',
            field=models.CharField(blank=True, choices=[('video_inicial', 'Video Inicial'), ('formulario_temas', 'Formulario de Temas'), ('preguntas_tema', 'Preguntas sobre Tema'), ('video_respuesta', 'Video de Respuesta'), ('tratamientos', 'Tratamientos'), ('diagnosticos', 'Diagnósticos')], default='video_inicial', max_length=20, null=True, verbose_name='Tipo de Etapa'),
        ),
        migrations.CreateModel(
            name='TemaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tema')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(default='fas fa-question', max_length=50, verbose_name='Icono FontAwesome')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='Caso_Clinico.etapa')),
            ],
            options={
                'verbose_name': 'Tema de Consulta',
                'verbose_name_plural': 'Temas de Consulta',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, verbose_name='Opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='Es respuesta correcta')),
                ('retroalimentacion', models.TextField(blank=True, verbose_name='Retroalimentación')),
                ('lleva_a_etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Caso_Clinico.etapa', verbose_name='Lleva a etapa')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='Caso_Clinico.temaconsulta')),
            ],
            options={
                'verbose_name': 'Opción de Tema',
                'verbose_name_plural': 'Opciones de Tema',
            },
        ),
    ]
