# Generated by Django 5.2.7 on 2025-10-31 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partes_cuerpo',
            name='Etapa',
        ),
        migrations.AddField(
            model_name='caso_clinico',
            name='Etapa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.etapa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caso_clinico',
            name='Paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.pacientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caso_clinico',
            name='ParteCuerpo',
            field=models.CharField(default=1, max_length=100, verbose_name='Parte del cuerpo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EtapaPaciente',
        ),
        migrations.DeleteModel(
            name='Partes_cuerpo',
        ),
    ]
