# Generated by Django 5.2.7 on 2025-10-31 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0002_remove_partes_cuerpo_etapa_caso_clinico_etapa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso_clinico',
            name='Etapa',
        ),
        migrations.RemoveField(
            model_name='caso_clinico',
            name='Paciente',
        ),
        migrations.AddField(
            model_name='etapa',
            name='Paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.pacientes'),
            preserve_default=False,
        ),
    ]
