# Generated by Django 5.2.7 on 2025-12-06 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0002_alter_etapa_options_etapa_orden_etapa_tema_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['ParteCuerpo', 'orden'], 'verbose_name': 'Etapa', 'verbose_name_plural': 'Etapas'},
        ),
        migrations.AlterModelOptions(
            name='partes_paciente',
            options={'verbose_name': 'Relación Paciente-Parte', 'verbose_name_plural': 'Relaciones Paciente-Parte'},
        ),
        migrations.AlterModelOptions(
            name='preguntaetapa',
            options={'verbose_name': 'Pregunta de Etapa', 'verbose_name_plural': 'Preguntas de Etapa'},
        ),
        migrations.AlterModelOptions(
            name='respuestaetapa',
            options={'verbose_name': 'Respuesta de Etapa', 'verbose_name_plural': 'Respuestas de Etapa'},
        ),
        migrations.AlterModelOptions(
            name='temaconsulta',
            options={'ordering': ['etapa', 'orden'], 'verbose_name': 'Tema de Consulta', 'verbose_name_plural': 'Temas de Consulta'},
        ),
        migrations.AddField(
            model_name='respuestaetapa',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Texto de respuesta'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre Etapa'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='orden',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='tipo',
            field=models.CharField(choices=[('video_inicial', 'Video Inicial'), ('formulario_temas', 'Formulario de Temas'), ('preguntas_tema', 'Preguntas sobre Tema'), ('video_respuesta', 'Video de Respuesta'), ('tratamientos', 'Tratamientos'), ('diagnosticos', 'Diagnósticos')], default='video_inicial', max_length=20, verbose_name='Tipo de Etapa'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='URL del Video'),
        ),
        migrations.AlterField(
            model_name='opciontema',
            name='es_correcta',
            field=models.BooleanField(default=False, verbose_name='Es correcta'),
        ),
        migrations.AlterField(
            model_name='opciontema',
            name='lleva_a_etapa',
            field=models.ForeignKey(blank=True, help_text='Etapa a la que redirige si se selecciona esta opción', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Caso_Clinico.etapa'),
        ),
        migrations.AlterField(
            model_name='opciontema',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='Caso_Clinico.temaconsulta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opciontema',
            name='texto',
            field=models.TextField(verbose_name='Texto de la opción'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='prevision',
            field=models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Particular', 'Particular/Privado'), ('Otro', 'Otro'), ('No aplica', 'No aplica')], default='Fonasa', max_length=50, verbose_name='Previsión'),
        ),
        migrations.AlterField(
            model_name='preguntaetapa',
            name='Etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Caso_Clinico.etapa'),
        ),
        migrations.AlterField(
            model_name='preguntaetapa',
            name='pregunta',
            field=models.TextField(default=1, verbose_name='Pregunta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respuestaetapa',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='Correcta'),
        ),
        migrations.AlterField(
            model_name='respuestaetapa',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='Caso_Clinico.preguntaetapa'),
        ),
        migrations.AlterField(
            model_name='respuestaetapa',
            name='retroalimentacion',
            field=models.TextField(verbose_name='Retroalimentación'),
        ),
        migrations.AlterField(
            model_name='temaconsulta',
            name='etapa',
            field=models.ForeignKey(default=1, limit_choices_to={'tipo': 'formulario_temas'}, on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='Caso_Clinico.etapa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temaconsulta',
            name='icono',
            field=models.CharField(default='fas fa-question-circle', max_length=50, verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='temaconsulta',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Tema'),
        ),
        migrations.AlterField(
            model_name='temaconsulta',
            name='orden',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('ParteCuerpo', 'orden')},
        ),
    ]
