# Generated by Django 5.2.7 on 2025-12-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0003_alter_etapa_options_alter_partes_paciente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaetapa',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='opciontema',
            name='video_respuesta',
            field=models.URLField(blank=True, help_text='URL de YouTube para respuesta correcta', null=True, verbose_name='Video de respuesta'),
        ),
        migrations.DeleteModel(
            name='PreguntaEtapa',
        ),
        migrations.DeleteModel(
            name='RespuestaEtapa',
        ),
    ]
