# Generated by Django 5.2.7 on 2025-10-31 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0003_remove_caso_clinico_etapa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso_clinico',
            name='ParteCuerpo',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='Paciente',
        ),
        migrations.CreateModel(
            name='CasoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.caso_clinico')),
                ('Pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Partes_cuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParteCuerpo', models.CharField(max_length=100, verbose_name='Parte del cuerpo')),
                ('CasoClinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.caso_clinico')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.pacientes')),
            ],
        ),
    ]
