# Generated by Django 5.2.7 on 2025-12-11 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0004_remove_respuestaetapa_pregunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='opciontema',
            name='lleva_a_etapa',
        ),
        migrations.AlterField(
            model_name='etapa',
            name='tipo',
            field=models.CharField(choices=[('video_inicial', 'Video Inicial'), ('formulario_temas', 'Formulario de Temas'), ('tratamientos', 'Tratamientos'), ('diagnosticos', 'Diagnósticos')], default='video_inicial', max_length=20, verbose_name='Tipo de Etapa'),
        ),
        migrations.AlterField(
            model_name='opciontema',
            name='texto',
            field=models.TextField(verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='opciontema',
            name='video_respuesta',
            field=models.URLField(blank=True, help_text='URL de YouTube para respuesta correcta', null=True, verbose_name='Video de respuesta correcta'),
        ),
        migrations.CreateModel(
            name='ContenidoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diagnostico', 'Diagnóstico'), ('tratamiento', 'Tratamiento')], max_length=20, verbose_name='Tipo de contenido')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('icono', models.CharField(default='fas fa-file-medical', max_length=50, verbose_name='Ícono')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='Caso_Clinico.etapa')),
            ],
            options={
                'verbose_name': 'Contenido de Etapa',
                'verbose_name_plural': 'Contenidos de Etapa',
                'ordering': ['etapa', 'orden'],
            },
        ),
    ]
