# Generated by Django 5.2.7 on 2025-10-31 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0004_remove_caso_clinico_partecuerpo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='Caso_clinico',
        ),
        migrations.AddField(
            model_name='etapa',
            name='ParetCuerpo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.partes_cuerpo'),
            preserve_default=False,
        ),
    ]
