# Generated by Django 5.2.7 on 2025-12-11 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0005_remove_etapa_tema_remove_opciontema_lleva_a_etapa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temaconsulta',
            name='icono',
        ),
        migrations.CreateModel(
            name='Diagnostico_Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diagnostico', 'Diagnóstico'), ('tratamiento', 'Tratamiento')], max_length=20, verbose_name='Tipo de contenido')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden')),
                ('etapa', models.ForeignKey(limit_choices_to={'tipo__in': ['diagnosticos', 'tratamientos']}, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='Caso_Clinico.etapa')),
            ],
            options={
                'verbose_name': 'Contenido de Etapa',
                'verbose_name_plural': 'Contenidos de Etapa',
                'ordering': ['etapa', 'orden'],
            },
        ),
        migrations.DeleteModel(
            name='ContenidoEtapa',
        ),
    ]
