# Generated by Django 5.2.7 on 2025-10-31 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0005_remove_etapa_caso_clinico_etapa_paretcuerpo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapa',
            old_name='ParetCuerpo',
            new_name='ParteCuerpo',
        ),
    ]
