# Generated by Django 5.2.7 on 2025-10-31 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0006_rename_paretcuerpo_etapa_partecuerpo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CasoPaciente',
            new_name='Partes_paciente',
        ),
        migrations.RemoveField(
            model_name='partes_cuerpo',
            name='Paciente',
        ),
        migrations.RemoveField(
            model_name='partes_paciente',
            name='Caso',
        ),
        migrations.AddField(
            model_name='partes_paciente',
            name='ParteCuerpo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.partes_cuerpo'),
            preserve_default=False,
        ),
    ]
