# Generated by Django 5.2.7 on 2025-12-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0006_remove_temaconsulta_icono_diagnostico_tratamiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostico_tratamiento',
            options={'ordering': ['etapa', 'orden'], 'verbose_name': 'Diagnóstico y tratamiento', 'verbose_name_plural': 'Diagnósticos y tratamientos'},
        ),
    ]
