# Generated by Django 5.2.7 on 2025-10-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0007_rename_casopaciente_partes_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='pregunta',
            field=models.CharField(max_length=150, null=True, verbose_name='Pregunta Etapa'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
