# Generated by Django 5.2.7 on 2025-10-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0008_alter_etapa_pregunta_alter_etapa_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='pregunta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Pregunta Etapa'),
        ),
    ]
