# Generated by Django 5.2.7 on 2025-11-13 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0009_alter_etapa_pregunta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caso_clinico',
            options={'verbose_name': 'Caso clínico', 'verbose_name_plural': 'Casos clínicos'},
        ),
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['nombre', 'ParteCuerpo'], 'verbose_name': 'Etapa', 'verbose_name_plural': 'Etapas'},
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={'ordering': ['fecha_nacimiento', 'nombre'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='partes_cuerpo',
            options={'verbose_name': 'Parte del cuerpo', 'verbose_name_plural': 'Partes del cuerpo'},
        ),
        migrations.AlterModelOptions(
            name='respuestaetapa',
            options={'ordering': ['pregunta'], 'verbose_name': 'Respuesta etapa', 'verbose_name_plural': 'Respuestas etapa'},
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestaetapa',
            name='Etapa',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='edad',
            field=models.IntegerField(default=4, verbose_name='Edad Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='ocupacion',
            field=models.CharField(default=1, max_length=100, verbose_name='Ocupación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='prevision',
            field=models.CharField(default=1, max_length=50, verbose_name='Previsión'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='partes_cuerpo',
            unique_together={('ParteCuerpo', 'CasoClinico')},
        ),
        migrations.CreateModel(
            name='PreguntaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pregunta Etapa')),
                ('Etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.etapa')),
            ],
            options={
                'verbose_name': 'Pregunta etapa',
                'verbose_name_plural': 'Preguntas etapa',
                'ordering': ['Etapa'],
            },
        ),
        migrations.AddField(
            model_name='respuestaetapa',
            name='pregunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Caso_Clinico.preguntaetapa'),
            preserve_default=False,
        ),
    ]
