# Generated by Django 5.2.7 on 2025-11-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0010_alter_caso_clinico_options_alter_etapa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntaetapa',
            options={'ordering': ['id', 'Etapa'], 'verbose_name': 'Pregunta etapa', 'verbose_name_plural': 'Preguntas etapa'},
        ),
        migrations.AlterModelOptions(
            name='respuestaetapa',
            options={'ordering': ['id', 'pregunta'], 'verbose_name': 'Respuesta etapa', 'verbose_name_plural': 'Respuestas etapa'},
        ),
    ]
