# Generated by Django 5.2.7 on 2025-11-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0011_alter_preguntaetapa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='prevision',
            field=models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre'), ('Particular', 'Particular/Privado'), ('Otro', 'Otro'), ('No aplica', 'No aplica')], default='FONASA', max_length=50, verbose_name='Previsión'),
        ),
    ]
