# Generated by Django 5.2.7 on 2025-11-20 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0012_alter_pacientes_prevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='ocupacion',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-\\.]*$', 'Este campo solo puede contener letras y espacios.')], verbose_name='Ocupación'),
        ),
    ]
