# Generated by Django 5.2.7 on 2025-11-20 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caso_Clinico', '0013_alter_pacientes_ocupacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partes_cuerpo',
            name='ParteCuerpo',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s\\-\\.]*$', 'Este campo solo puede contener letras y espacios.')], verbose_name='Parte del cuerpo'),
        ),
    ]
